### PR TITLE
added php documentation

### PR DESCRIPTION
**Pull request by rajeev-k-tomy**
I have added documentation for this extension. This is an awesome extension and I felt it looks "bored" without having documentation. So I invested some time for adding documentation. Please review it and if it is okay, merge it with your extension.

### CODE REVIEW

**Comment by philwinkle** [comment]
Great idea - but let's fix a few things:
- Philipwinkle should be "Philwinkle" in all files
- Remove the file info section e.g. "File: Pathes.php" (btw, many misspellings here, too, as it should be Patches.php)

**Comment by rajeev-k-tomy** [comment]
Yup. I will do this. Btw, what would you like to give as documentation header ??

What about `Philwinkle_AppliedPatches Magento Extension` ? Is that look nice as documentation heading ?

**Comment by rajeev-k-tomy** [comment]
See my next pull request and let me know your feedback on this.

**Comment by philwinkle** [comment]
Hey man. Sorry can you rebase this?

**Comment by rajeev-k-tomy** [comment]
Hey Phil, Just rebased and updated my repo. You can use the pull request with message `Rebased pull request` that you can find above.

**Pull request merged**
